/* Demo14 full_project main.c
 * Implements short press / long press detection using EXTI on PA0 and HAL_GetTick timing
 * Uses an RTOS task to process events generated by EXTI callback
 */

#include "main.h"
#include "cmsis_os2.h"
#include <stdio.h>

static osThreadId_t keyTaskHandle;

volatile uint32_t key_press_time = 0;

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin == KEY_Pin) {
        if (HAL_GPIO_ReadPin(KEY_GPIO_Port, KEY_Pin) == GPIO_PIN_RESET) {
            // pressed (active low)
            key_press_time = HAL_GetTick();
        } else {
            // released
            uint32_t dt = HAL_GetTick() - key_press_time;
            if (dt >= 2000) {
                osThreadFlagsSet(keyTaskHandle, 0x04); // very long
            } else if (dt >= 1000) {
                osThreadFlagsSet(keyTaskHandle, 0x02); // long
            } else {
                osThreadFlagsSet(keyTaskHandle, 0x01); // short
            }
        }
    }
}

void KeyTask(void *arg)
{
    for(;;) {
        uint32_t flags = osThreadFlagsWait(0x07, osFlagsWaitAny, osWaitForever);
        if (flags & 0x01) printf("short press\r\n");
        if (flags & 0x02) printf("long press\r\n");
        if (flags & 0x04) printf("very long press\r\n");
    }
}

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();

    osKernelInitialize();
    const osThreadAttr_t attr = { .name = "key", .stack_size = 256*4, .priority = osPriorityNormal };
    keyTaskHandle = osThreadNew(KeyTask, NULL, &attr);
    osKernelStart();
    while (1) {}
}
